/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import dao.ArtistaDao;
import Controlador.conciertoController;
import modelo.Artistas;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Concierto;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.regex.Pattern;
/**
 *
 * @author ixpat
 */
public class jpConcierto extends javax.swing.JPanel {
    
    private conciertoController conciertoController;
    private ArtistaDao artistaDao;
    private List<Artistas> listaArtistas;
    private TableRowSorter<DefaultTableModel> sorter;
   public jpConcierto() {
          initComponents();

        conciertoController =
                new conciertoController();

        artistaDao =
                new ArtistaDao();

        cargarArtistas();

        cargarTabla();
        
        configurarBusqueda();
    }
    
    private void cargarArtistas() {

         listaArtistas = artistaDao.listar();

         cmbxArtista.removeAllItems();

        for (Artistas artista : listaArtistas) {
            cmbxArtista.addItem(artista.getNombreArtistico());
        }
    }


    private void limpiarCampos() {

        txtID.setText("");
        txtTituloEvento.setText("");
        txtFechaConcierto.setText("");
        txtRecinto.setText("");

        if (cmbxArtista.getItemCount() > 0) {
            cmbxArtista.setSelectedIndex(0);
        }

        cmbxEstado.setSelectedIndex(0);
    }
    private void cargarTabla() {

        DefaultTableModel modelo =
                (DefaultTableModel) tblConciertos.getModel();

        modelo.setRowCount(0);

        List<Concierto> lista =
                conciertoController.listar();

        for (Concierto concierto : lista) {

            String nombreArtista = "";

            for (Artistas artista : listaArtistas) {

                if (artista.getIdArtista()
                        == concierto.getIdArtista()) {

                    nombreArtista =
                            artista.getNombreArtistico();

                    break;
                }
            }

            Object[] fila = {

                concierto.getIdConcierto(),
                nombreArtista,
                concierto.getTituloEvento(),
                concierto.getFechaConcierto(),
                concierto.getRecinto(),
                concierto.getEstado()
            };

            modelo.addRow(fila);
        }
    }
    private void configurarBusqueda() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblConciertos.getModel();

        sorter = new TableRowSorter<>(modelo);

        tblConciertos.setRowSorter(sorter);

        txtBuscar.getDocument().addDocumentListener(
                new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrar();
            }
        });
    }
    private void filtrar() {

        String texto = txtBuscar.getText().trim();

        if (texto.isEmpty()) {

            sorter.setRowFilter(null);

        } else {

            sorter.setRowFilter(
                RowFilter.regexFilter(
                    "(?i)" + Pattern.quote(texto)
                )
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbxArtista = new javax.swing.JComboBox<>();
        cmbxEstado = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConciertos = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtTituloEvento = new javax.swing.JTextField();
        txtFechaConcierto = new javax.swing.JTextField();
        txtRecinto = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jInternalFrame1.setTitle("Conciertos");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(425, 488));
        jInternalFrame1.setRequestFocusEnabled(false);
        jInternalFrame1.setVisible(true);

        jLabel1.setText("ID:");

        jLabel2.setText("Artista:");

        jLabel3.setText("Titulo del Evento");

        jLabel4.setText("Fecha de concierto");

        jLabel5.setText("Recinto");

        jLabel6.setText("Estado");

        cmbxArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtBuscar.setText("Bucar concierto...                                                   ");
        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        tblConciertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConciertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConciertosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConciertos);

        txtID.setText("Automatico");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(130, 130, 130)
                        .addComponent(txtRecinto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(24, 24, 24)
                        .addComponent(btnGuardar)
                        .addGap(28, 28, 28)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(70, 70, 70)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaConcierto)
                            .addComponent(txtTituloEvento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int posicion = cmbxArtista.getSelectedIndex();

        if (posicion == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un artista");
            return;
        }

        Artistas artista = listaArtistas.get(posicion);

        Concierto concierto = new Concierto();

        concierto.setIdArtista(artista.getIdArtista());
        concierto.setTituloEvento(txtTituloEvento.getText());
        concierto.setFechaConcierto(txtFechaConcierto.getText());
        concierto.setRecinto(txtRecinto.getText());
        concierto.setEstado(cmbxEstado.getSelectedItem().toString());

        boolean resultado = conciertoController.guardar(concierto);

        if (resultado) {

            JOptionPane.showMessageDialog(this,
                    "Concierto guardado correctamente");

            limpiarCampos();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Error al guardar el concierto");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtID.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Seleccione un concierto");

            return;
        }

        int posicion = cmbxArtista.getSelectedIndex();

        if (posicion == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un artista");
            return;
        }

        Artistas artista = listaArtistas.get(posicion);

        Concierto concierto = new Concierto();

        concierto.setIdConcierto(
                Integer.parseInt(txtID.getText()));

        concierto.setIdArtista(
                artista.getIdArtista());

        concierto.setTituloEvento(
                txtTituloEvento.getText());

        concierto.setFechaConcierto(
                txtFechaConcierto.getText());

        concierto.setRecinto(
                txtRecinto.getText());

        concierto.setEstado(
                cmbxEstado.getSelectedItem().toString());

        boolean resultado =
                conciertoController.actualizar(concierto);

        if (resultado) {

            JOptionPane.showMessageDialog(this,
                    "Concierto actualizado correctamente");

            limpiarCampos();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Error al actualizar");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (txtID.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Seleccione un concierto");

            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este concierto?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(txtID.getText());

            boolean resultado =
                    conciertoController.eliminar(id);

            if (resultado) {

                JOptionPane.showMessageDialog(this,
                        "Concierto eliminado correctamente");

                limpiarCampos();

            } else {

                JOptionPane.showMessageDialog(this,
                        "No se pudo eliminar el concierto");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblConciertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConciertosMouseClicked
           int fila = tblConciertos.getSelectedRow();

        if (fila == -1) {
            return;
        }

        txtID.setText(
                tblConciertos.getValueAt(fila, 0).toString());

        String nombreArtista =
                tblConciertos.getValueAt(fila, 1).toString();

        cmbxArtista.setSelectedItem(nombreArtista);

        txtTituloEvento.setText(
                tblConciertos.getValueAt(fila, 2).toString());

        txtFechaConcierto.setText(
                tblConciertos.getValueAt(fila, 3).toString());

        txtRecinto.setText(
                tblConciertos.getValueAt(fila, 4).toString());

        cmbxEstado.setSelectedItem(
                tblConciertos.getValueAt(fila, 5).toString());
    
    }//GEN-LAST:event_tblConciertosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbxArtista;
    private javax.swing.JComboBox<String> cmbxEstado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConciertos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFechaConcierto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRecinto;
    private javax.swing.JTextField txtTituloEvento;
    // End of variables declaration//GEN-END:variables
}
